#!/bin/sh

# get transaction (snapshot will be made here)
curl -s http://127.0.0.1:5004/get_tx > /tmp/get_tx
# print it for debugging
echo "Transaction:"

cat /tmp/get_tx

echo ""

# Upload to IPFS MFS /state/output
curl -X POST -F file=@/tmp/get_tx "http://127.0.0.1:5001/api/v0/files/write?arg=/state/output&create=1&truncate=1"

# signal we are done and /state in current condition is final
curl -X POST http://127.0.0.1:5004/finish
